In [1]:
import pandas as pd
import numpy as np
import time


In [6]:
class1 = np.array([[1,1],[1,2],[2,1],[1,0]])
class2 = np.array([[2,3],[2,2],[3,3],[3,0]])

In [7]:
class1.mean(axis  = 0), class2.mean(axis=0)

(array([1.25, 1.  ]), array([2.5, 2. ]))

In [5]:
np.cov(class2.T)*(3)

array([[ 1., -1.],
       [-1.,  6.]])

In [11]:
1.25**2 + 1+2.5**2 + 2**2 

12.8125

In [13]:
-2*(1.25+ 2.5)

-7.5

In [16]:
0.75**2 +3*0.625 +1

3.4375

In [8]:
x = np.array([[1.75,-1],[-1,8]])
display(x)
x_inv = np.linalg.inv(x)
w = x_inv @ np.array([[-1.25],[-1]])
w

array([[ 1.75, -1.  ],
       [-1.  ,  8.  ]])

array([[-0.84615385],
       [-0.23076923]])

In [4]:
x_inv

array([[0.61538462, 0.07692308],
       [0.07692308, 0.13461538]])

In [9]:
c1 = w.transpose() @ class1.T
c2 = w.transpose() @ class2.T

c1.mean(), c2.mean()


(-1.288461538461538, -2.5769230769230766)

In [10]:
c1, c2

(array([[-1.07692308, -1.30769231, -1.92307692, -0.84615385]]),
 array([[-2.38461538, -2.15384615, -3.23076923, -2.53846154]]))

In [12]:
test = np.array([[2],[1.4]])
proj_test = w.transpose() @ test
proj_test

array([[-2.01538462]])

In [13]:
abs(proj_test - c1.mean()), abs(proj_test - c2.mean())

(array([[0.72692308]]), array([[0.56153846]]))

In [16]:
abs(c2 - proj_test) 

array([[0.36923077, 0.13846154, 1.21538462, 0.52307692]])

In [38]:
0.75**2 +0.4**2

0.7225

In [39]:
0.5**2 +0.6**2

0.61

## PCA

In [99]:
entire_set = np.vstack((class1,class2))
cov_entireset = np.cov(entire_set.T)
cov_entireset

array([[0.69642857, 0.21428571],
       [0.21428571, 1.42857143]])

In [100]:
w, v = np.linalg.eig(cov_entireset)
w, v


(array([0.63832237, 1.48667763]),
 array([[-0.96514622, -0.26171123],
        [ 0.26171123, -0.96514622]]))

In [101]:
test_proj_pca = v[:,1].T @ test
test_proj_pca

array([-1.87462716])

In [108]:
dist = (v[:,1] @ class2.T)
dist

array([-3.41886112, -2.4537149 , -3.68057235, -0.78513368])

In [107]:
dist = (v[:,1] @ class2.T) - test_proj_pca
abs(dist)

array([1.54423396, 0.57908773, 1.80594518, 1.08949349])